[package]
name = "configctl"
version = "0.3.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
dirs = "6.0.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
